// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktykrwukmbkepnnhdqcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0eWtyd3VrbWJrZXBubmhkcWNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0NTU2NzUsImV4cCI6MjA1NjAzMTY3NX0.T9hAaly8KlHVc_brV6TsLfSC99l9F_6o9yXnG8EgksQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);